"""Shared figure style. Every figure in the paper is generated by a script.

Four rules, enforced here rather than remembered per figure:

**Vector output at print size.** Figures are written as PDF at the width of a
single or double journal column, with fonts sized so that the *final printed*
text is 7-9 pt. Sizing a figure on screen and shrinking it later is how axis
labels end up unreadable, which is one of the defects this rebuild is
correcting in the original paper.

**Colourblind-safe.** The palette is Okabe-Ito, which is distinguishable under
deuteranopia, protanopia and tritanopia. No red/green pairs carry meaning.

**Never colour alone.** :func:`series` returns a colour *and* a marker *and* a
linestyle, and every plotting helper uses all three. A reader printing in
greyscale, or a reviewer with a monochrome PDF, loses nothing. Hatching plays
the same role for bars.

**Perceptually uniform heatmaps.** Confusion matrices use `cividis`, which is
both colourblind-safe and monotonic in lightness, so the greyscale rendering
preserves the ordering.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Sequence, Tuple

__all__ = [
    "OKABE_ITO",
    "MARKERS",
    "LINESTYLES",
    "HATCHES",
    "series",
    "use_style",
    "new_figure",
    "save",
    "COLUMN_WIDTH",
    "DOUBLE_WIDTH",
]

# Okabe & Ito (2008), "Color Universal Design". Black first: a single-series
# figure should be black, not an arbitrary colour.
OKABE_ITO = (
    "#000000",  # black
    "#E69F00",  # orange
    "#56B4E9",  # sky blue
    "#009E73",  # bluish green
    "#F0E442",  # yellow
    "#0072B2",  # blue
    "#D55E00",  # vermillion
    "#CC79A7",  # reddish purple
)
MARKERS = ("o", "s", "^", "D", "v", "P", "X", "*")
LINESTYLES = (
    "-",
    (0, (4, 1.5)),
    (0, (1, 1.2)),
    (0, (5, 1.2, 1, 1.2)),
    (0, (3, 1, 1, 1, 1, 1)),
    (0, (7, 2)),
    (0, (2, 1)),
    (0, (6, 1, 2, 1)),
)
HATCHES = ("", "///", "...", "\\\\\\", "xxx", "---", "+++", "ooo")

# Widths in inches. Most journals set a single column near 3.5in and a double
# column near 7.16in; these are the safe common values.
COLUMN_WIDTH = 3.5
DOUBLE_WIDTH = 7.16


def series(index: int) -> Dict[str, object]:
    """Colour, marker and linestyle for series ``index``.

    Returned together on purpose. Taking only the colour is what produces a
    figure that is unreadable in greyscale, so the call site has to opt out
    deliberately rather than by omission.
    """
    return {
        "color": OKABE_ITO[index % len(OKABE_ITO)],
        "marker": MARKERS[index % len(MARKERS)],
        "linestyle": LINESTYLES[index % len(LINESTYLES)],
    }


def use_style() -> None:
    """Apply the shared rcParams. Idempotent; call once per script."""
    import matplotlib

    matplotlib.use("Agg")  # no display on this machine, and none is needed
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
        # Type 42 = TrueType. Type 3 fonts are rejected by several publishers
        # and are matplotlib's PDF default.
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans", "Arial", "Helvetica"],
        "font.size": 8,
        "axes.titlesize": 8.5,
        "axes.labelsize": 8,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "legend.frameon": False,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "grid.linewidth": 0.5,
        "lines.linewidth": 1.3,
        "lines.markersize": 4,
        "errorbar.capsize": 2,
    })


def new_figure(width: float = COLUMN_WIDTH, height: float = 2.4, **kwargs):
    import matplotlib.pyplot as plt

    return plt.subplots(figsize=(width, height), **kwargs)


def save(fig, name: str, root: Path | str = "figures") -> Tuple[Path, Path]:
    """Write ``name`` as PDF (for the manuscript) and PNG (for quick reading).

    The PDF is the deliverable; the PNG exists so a figure can be checked
    without opening a viewer, and is never what gets submitted.
    """
    import matplotlib.pyplot as plt

    directory = Path(root)
    directory.mkdir(parents=True, exist_ok=True)
    pdf = directory / f"{name}.pdf"
    png = directory / f"{name}.png"
    fig.savefig(pdf)
    fig.savefig(png)
    plt.close(fig)
    return pdf, png


def annotate_floor(axis, value: float, label: str = "chance", x: float = 0.995,
                   **kwargs) -> None:
    """Draw a floor as a labelled dotted line.

    Floors are drawn on every performance axis. A macro-F1 of 0.30 means
    nothing without the 0.167 chance line next to it, and the original paper
    reported figures with no floor at all.
    """
    axis.axhline(value, color="0.35", linestyle=(0, (1, 2)), linewidth=1.0, zorder=0)
    axis.annotate(
        f"{label} {value:.3f}",
        xy=(x, value),
        xycoords=("axes fraction", "data"),
        ha="right" if x > 0.5 else "left",
        va="bottom", fontsize=6, color="0.35",
        **kwargs,
    )
