"""Effective rank of the source-train covariance, per backbone and per layer.

Two estimators, both reported, because they answer slightly different questions
and disagreeing is informative:

**Spectral entropy** (Roy & Vetterli 2007) — ``exp(-Σ pᵢ log pᵢ)`` over the
normalised eigenvalue spectrum ``pᵢ = λᵢ/Σλ``. The exponential of the spectral
entropy: how many directions carry energy, weighted by how evenly.

**Participation ratio** — ``(Σλᵢ)² / Σλᵢ²``. More sensitive to the largest
eigenvalues, so it reads lower than spectral entropy when a handful of
directions dominate.

Both are continuous, unlike a thresholded numerical rank, so they distinguish
"768 directions with energy spread evenly" from "768 directions where fifty
carry everything" — the distinction that decides whether whitening a covariance
is numerically meaningful.

This is a diagnostic on the *features*, not on any model, so it needs no
classifier and no alignment fit.
"""

from __future__ import annotations

from typing import Dict, List, Sequence

import numpy as np

from .features.load import FeatureLoader
from .manifest import read_manifest
from .numerics import covariance, diagnose
from .splits import make_pair_split

__all__ = ["participation_ratio", "run_rank_report"]


def participation_ratio(eigenvalues: np.ndarray) -> float:
    """``(Σλ)² / Σλ²``. Equals d for a flat spectrum, 1 for a rank-1 one."""
    eigenvalues = np.clip(np.asarray(eigenvalues, dtype=np.float64), 0.0, None)
    total = float(eigenvalues.sum())
    if total <= 0:
        return 0.0
    return float(total**2 / float((eigenvalues**2).sum()))


def run_rank_report(config, corpora: Sequence[str], *, seed: int = 0) -> int:
    rows = read_manifest(config.resolve(config.paths.manifest))
    present = [name for name in corpora if any(r.corpus == name for r in rows)]
    backbones = [b for b in config.features.backbones]
    n_layers = config.features.n_layers

    records: List[Dict] = []
    for corpus in present:
        # source_train of the in-domain split: the matrix an actual run fits on.
        pair = make_pair_split(rows, config, corpus, corpus, seed)
        ids = pair.source_train.utterance_ids
        for backbone in backbones:
            loader = FeatureLoader(config, corpus, backbone, rows)
            for layer in range(n_layers):
                X = loader.load(ids, layer_spec=f"layer:{layer}")
                cov = covariance(X, name=f"{corpus}/{backbone}/layer:{layer}")
                diagnostics = diagnose(cov, n_samples=X.shape[0])
                eigenvalues = np.linalg.eigvalsh(cov)
                records.append(
                    {
                        "corpus": corpus,
                        "backbone": backbone,
                        "layer": layer,
                        "n_samples": X.shape[0],
                        "n_features": X.shape[1],
                        "spectral_entropy_rank": diagnostics.effective_rank,
                        "participation_ratio": participation_ratio(eigenvalues),
                        "numerical_rank": diagnostics.numerical_rank,
                        "condition_number": diagnostics.condition_number,
                    }
                )
        print(f"  {corpus}: {len(backbones)} backbones x {n_layers} layers done", flush=True)

    _write_report(config, records, present, backbones, n_layers)

    print()
    print("spectral-entropy effective rank (of 768), source_train")
    header = f"{'corpus':<9} {'backbone':<9} " + " ".join(f"{i:>5}" for i in range(n_layers))
    print(header)
    for corpus in present:
        for backbone in backbones:
            values = [
                r["spectral_entropy_rank"]
                for r in records
                if r["corpus"] == corpus and r["backbone"] == backbone
            ]
            print(
                f"{corpus:<9} {backbone:<9} " + " ".join(f"{v:5.1f}" for v in values)
            )
    return 0


def _write_report(config, records, present, backbones, n_layers) -> None:
    lines = ["# Effective rank of the source-train covariance", ""]
    lines.append(
        "Per backbone, per layer, on the `source_train` split of each corpus's "
        "in-domain pair at seed 0 — the matrix an actual run fits on. "
        "Generated by `ser effective-rank`."
    )
    lines.append("")
    lines.append("## Estimators")
    lines.append("")
    lines.append(
        "**Spectral entropy** (Roy & Vetterli 2007): `exp(-Σ pᵢ log pᵢ)` with "
        "`pᵢ = λᵢ/Σλ`. This is the estimator reported in the `cov_effective_rank` "
        "column of `results/runs.jsonl`."
    )
    lines.append("")
    lines.append(
        "**Participation ratio**: `(Σλᵢ)² / Σλᵢ²`. Weighted more towards the "
        "largest eigenvalues, so it reads lower when a few directions dominate."
    )
    lines.append("")
    lines.append(
        "Both are continuous, unlike a thresholded numerical rank, so they "
        "separate 'energy spread evenly' from 'a handful of directions carry "
        "everything' — which is what decides whether whitening is meaningful."
    )
    lines.append("")

    for name, key in (
        ("Spectral-entropy effective rank", "spectral_entropy_rank"),
        ("Participation ratio", "participation_ratio"),
    ):
        lines.append(f"## {name}")
        lines.append("")
        lines.append(
            "| corpus | backbone | n | " + " | ".join(f"L{i}" for i in range(n_layers)) + " |"
        )
        lines.append("|---" * (n_layers + 3) + "|")
        for corpus in present:
            for backbone in backbones:
                matching = [
                    r for r in records if r["corpus"] == corpus and r["backbone"] == backbone
                ]
                if not matching:
                    continue
                values = " | ".join(f"{r[key]:.1f}" for r in matching)
                lines.append(
                    f"| {corpus} | {backbone} | {matching[0]['n_samples']} | {values} |"
                )
        lines.append("")

    lines.append("## Reading this")
    lines.append("")
    lines.append(
        "Nominal dimension is 768 throughout. Where the effective rank is a small "
        "fraction of that, CORAL is whitening a badly degenerate matrix and the "
        "shrinkage `eps` is not a numerical nicety but the thing deciding what the "
        "transform does. Layer 0 is the CNN feature-encoder output; layers 1–12 are "
        "the transformer blocks."
    )
    lines.append("")

    out = config.resolve(config.paths.reports_dir) / "effective_rank.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    import csv

    with open(
        config.resolve(config.paths.reports_dir) / "effective_rank.csv",
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=list(records[0].keys()))
        writer.writeheader()
        writer.writerows(records)
