"""Build every split, run the leakage assertions, and report split-level priors.

This is the A9 deliverable in reporting form: corpus-level prior KL is a
data-integrity check against published counts, but the quantity that governs a
run is the divergence between the *realised* ``source_train`` prior and the
*realised* ``target_test`` prior, which varies by seed. Both are shown side by
side so the difference is visible rather than assumed.
"""

from __future__ import annotations

import statistics
from itertools import product
from typing import Dict, List, Sequence

from .datastats import kl_divergence, prior_vector, space_for_pair
from .leakage import check_pair_split
from .manifest import read_manifest
from .splits import ROLES, make_pair_split, split_class_counts

__all__ = ["run_splits_report", "pair_split_summary"]


def pair_split_summary(rows, config, source: str, target: str, seed: int) -> Dict:
    """Build one pair split and summarise it."""
    pair = make_pair_split(rows, config, source, target, seed)
    classes = config.labels.spaces[pair.label_space]

    priors = {}
    counts = {}
    for role in ROLES:
        role_counts = split_class_counts(rows, pair.splits()[role], pair.label_space)
        counts[role] = role_counts
        priors[role] = prior_vector(role_counts, classes)

    split_kl = None
    if priors["source_train"] and priors["target_test"]:
        split_kl = kl_divergence(priors["source_train"], priors["target_test"])

    return {
        "pair": pair,
        "problems": check_pair_split(pair),
        "sizes": pair.sizes(),
        "counts": counts,
        "priors": priors,
        "split_kl": split_kl,
        "classes": classes,
    }


def run_splits_report(config, corpora: Sequence[str]) -> int:
    rows = read_manifest(config.resolve(config.paths.manifest))
    present = [name for name in corpora if any(r.corpus == name for r in rows)]
    seeds = list(config.splits.seeds)

    summaries: List[Dict] = []
    for source, target in product(present, repeat=2):
        for seed in seeds:
            summaries.append(pair_split_summary(rows, config, source, target, seed))

    problems = [p for summary in summaries for p in summary["problems"]]

    lines = _render(config, rows, present, seeds, summaries, problems)
    out = config.resolve(config.paths.reports_dir) / "splits.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"pairs: {len(present)**2} | seeds: {len(seeds)} | splits built: {len(summaries)}")
    print()
    print("leakage assertions:", "ALL PASS" if not problems else f"{len(problems)} FAILURE(S)")
    for problem in problems[:10]:
        print(f"  - {problem}")
    print()

    print("split-level prior KL, source_train || target_test  (A9)")
    print(f"{'pair':<22} {'mean':>8} {'min':>8} {'max':>8}   corpus-level")
    for source, target in product(present, repeat=2):
        values = [
            s["split_kl"]
            for s in summaries
            if s["pair"].source_corpus == source
            and s["pair"].target_corpus == target
            and s["split_kl"] is not None
        ]
        if not values:
            continue
        corpus_kl = _corpus_level_kl(rows, config, source, target)
        print(
            f"{source + ' -> ' + target:<22} {statistics.fmean(values):8.4f} "
            f"{min(values):8.4f} {max(values):8.4f}   "
            f"{'—' if corpus_kl is None else f'{corpus_kl:.4f}'}"
        )
    print()
    print(f"wrote {out}")

    return 1 if problems else 0


def _corpus_level_kl(rows, config, source: str, target: str):
    label_space = space_for_pair(config, source, target)
    classes = config.labels.spaces[label_space]
    from .datastats import class_counts

    p = prior_vector(class_counts(rows, source, label_space), classes)
    q = prior_vector(class_counts(rows, target, label_space), classes)
    if p is None or q is None:
        return None
    return kl_divergence(p, q)


def _render(config, rows, present, seeds, summaries, problems) -> List[str]:
    lines = ["# Splits and leakage assertions", ""]
    lines.append(
        "Generated by `ser splits`. Every number derives from `data/manifest.csv` "
        "plus the seeds in `configs/default.yaml`."
    )
    lines.append("")

    lines.append("## Leakage assertions")
    lines.append("")
    lines.append(
        "1. No speaker (or session) appears in more than one split within a corpus.\n"
        "2. No utterance appears in both a source split and a target split.\n"
        "3. `target_test` never appears in any fitted alignment object — a contract "
        "on Phase 5, asserted in `ser.leakage.assert_alignment_blind_to_target_test`.\n"
        "4. `map_label` is pure — asserted in `tests/test_labelmap.py`."
    )
    lines.append("")
    if problems:
        lines.append(f"> ⚠️ **{len(problems)} FAILURE(S)**")
        lines.append("")
        for problem in problems:
            lines.append(f"- {problem}")
    else:
        lines.append(
            f"**All assertions pass** over {len(summaries)} splits "
            f"({len(present)**2} pairs × {len(seeds)} seeds)."
        )
    lines.append("")

    lines.append("## Split sizes")
    lines.append("")
    lines.append("Seed 0 shown; sizes vary by seed within the speaker-disjoint constraint.")
    lines.append("")
    lines.append("| pair | space | " + " | ".join(ROLES) + " |")
    lines.append("|---" * (len(ROLES) + 2) + "|")
    for summary in summaries:
        pair = summary["pair"]
        if pair.seed != seeds[0]:
            continue
        sizes = summary["sizes"]
        lines.append(
            f"| {pair.source_corpus} → {pair.target_corpus} | {pair.label_space} | "
            + " | ".join(str(sizes[role]) for role in ROLES)
            + " |"
        )
    lines.append("")

    lines.append("## Split-level prior shift (A9)")
    lines.append("")
    lines.append(
        "`KL(prior(source_train) || prior(target_test))` from the realised "
        "partitions, against the corpus-level figure. **The corpus-level number is "
        "not the quantity the analysis rests on**: splitting by speaker moves class "
        "proportions, and it moves them differently per seed."
    )
    lines.append("")
    lines.append("| pair | corpus-level KL | split-level mean | min | max | spread |")
    lines.append("|---|---|---|---|---|---|")
    for source, target in product(present, repeat=2):
        values = [
            s["split_kl"]
            for s in summaries
            if s["pair"].source_corpus == source
            and s["pair"].target_corpus == target
            and s["split_kl"] is not None
        ]
        if not values:
            continue
        corpus_kl = _corpus_level_kl(rows, config, source, target)
        lines.append(
            f"| {source} → {target} | "
            f"{'—' if corpus_kl is None else f'{corpus_kl:.4f}'} | "
            f"{statistics.fmean(values):.4f} | {min(values):.4f} | {max(values):.4f} | "
            f"{max(values) - min(values):.4f} |"
        )
    lines.append("")

    lines.append("## Per-seed split-level priors")
    lines.append("")
    for source, target in product(present, repeat=2):
        matching = [
            s
            for s in summaries
            if s["pair"].source_corpus == source and s["pair"].target_corpus == target
        ]
        if not matching:
            continue
        classes = matching[0]["classes"]
        lines.append(f"### {source} → {target}")
        lines.append("")
        lines.append(
            "| seed | role | " + " | ".join(classes) + " | n |"
        )
        lines.append("|---" * (len(classes) + 3) + "|")
        for summary in matching:
            for role in ("source_train", "target_test"):
                prior = summary["priors"][role]
                if prior is None:
                    continue
                lines.append(
                    f"| {summary['pair'].seed} | {role} | "
                    + " | ".join(f"{p:.3f}" for p in prior)
                    + f" | {summary['sizes'][role]} |"
                )
        lines.append("")

    return lines
